import { Employee, LeaveRequest, ComplianceAlert, NotificationItem, AuditLog, TimecardRecord } from '@/types';
import { encryptAES256 } from './crypto';

const getTodayFormatted = (): string => {
  const d = new Date();
  const day = String(d.getDate()).padStart(2, '0');
  const month = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'][d.getMonth()];
  const year = d.getFullYear();
  return `${day} ${month} ${year}`;
};

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-42',
    employeeNumber: 'EMP-0042',
    username: 'suman.thapa',
    firstName: 'Suman',
    lastName: 'Thapa',
    email: 'suman.thapa@company.com',
    mobilePhone: '0412 345 678',
    homePhone: '02 9876 5432',
    dateOfBirth: '14/08/1994',
    startDate: '15/05/2025',
    gender: 'Male',
    address: '14 Belmore Road',
    suburb: 'Riverwood',
    state: 'NSW',
    postcode: '2210',
    department: 'Production (Riverwood)',
    jobTitle: 'Production Specialist',
    workLocation: 'Riverwood, NSW',
    reportsTo: 'Binod Gurung',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    citizenStatus: 'VISA_HOLDER',
    visaType: 'Temporary Skill Shortage (Subclass 482)',
    visaExpiryDate: '30/08/2026',
    workRestrictions: 'Full-time work rights, 38 hours/week',
    hasDriverLicense: true,
    licenseCountry: 'Australia',
    licenseNumber: 'DL-9948210',
    licenseExpiryDate: '12/10/2027',
    emergencyNextOfKin: 'Pooja Thapa',
    emergencyRelationship: 'Spouse',
    emergencyAddress: '14 Belmore Road',
    emergencySuburb: 'Riverwood',
    emergencyState: 'NSW',
    emergencyPostcode: '2210',
    emergencyMobile: '0423 999 888',
    emergencyHomePhone: '02 9876 5432',
    tfnMasked: '• • • - • • • - 482',
    tfnEncrypted: encryptAES256('847291482'),
    superFundName: 'AustralianSuper',
    superMemberNumber: 'AUS-998241',
    bankName: 'Commonwealth Bank of Australia',
    bankBranch: 'Riverwood Branch',
    accountName: 'Suman Thapa',
    bsbMasked: '062-•••',
    bsbEncrypted: encryptAES256('062-184'),
    accountNumberMasked: '••••••789',
    accountNumberEncrypted: encryptAES256('104856789'),
    leaveBalance: {
      annual: 8,
      sick: 10,
      carers: 2,
      longService: 15,
    },
    payslips: [
      {
        id: 'ps-01',
        payPeriod: '01 May 2025 - 15 May 2025',
        payDate: '16/05/2025',
        grossPay: 1650.00,
        taxDeductions: 404.20,
        superannuation: 181.50,
        netPay: 1245.80,
        status: 'Paid',
      },
      {
        id: 'ps-02',
        payPeriod: '16 Apr 2025 - 30 Apr 2025',
        payDate: '01/05/2025',
        grossPay: 1650.00,
        taxDeductions: 404.20,
        superannuation: 181.50,
        netPay: 1245.80,
        status: 'Paid',
      }
    ],
    documents: [
      { id: 'doc-1', name: 'Passport Copy', type: 'Identification', uploadDate: '10/05/2025', status: 'Verified', fileSize: '2.4 MB' },
      { id: 'doc-2', name: 'TFN Declaration', type: 'Tax & Compliance', uploadDate: '10/05/2025', status: 'Verified', fileSize: '1.1 MB' },
      { id: 'doc-3', name: 'Bank Account Confirmation', type: 'Payroll', uploadDate: '10/05/2025', status: 'Verified', fileSize: '850 KB' },
      { id: 'doc-4', name: 'Driving License Copy', type: 'License', uploadDate: '12/05/2025', status: 'Pending', fileSize: '3.1 MB' },
      { id: 'doc-5', name: 'Signed Resume & CV', type: 'HR Onboarding', uploadDate: '10/05/2025', status: 'Verified', fileSize: '1.8 MB' },
    ],
    kioskPin: '4829',
    clockState: 'CLOCKED_IN',
    clockInTimestamp: Date.now() - (3 * 3600 + 42 * 60 + 15) * 1000,
    lastClockIn: new Date(Date.now() - (3 * 3600 + 42 * 60 + 15) * 1000).toISOString(),
    currentShiftId: 'tc-live-01',
  },
  {
    id: 'emp-41',
    employeeNumber: 'EMP-0041',
    username: 'anita.kc',
    firstName: 'Anita',
    lastName: 'KC',
    email: 'anita.kc@company.com',
    mobilePhone: '0423 456 789',
    dateOfBirth: '22/03/1996',
    startDate: '12/05/2025',
    gender: 'Female',
    address: '88 George Street',
    suburb: 'Parramatta',
    state: 'NSW',
    postcode: '2150',
    department: 'Design',
    jobTitle: 'Senior UI/UX Designer',
    workLocation: 'Sydney CBD, NSW',
    reportsTo: 'Creative Director',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    citizenStatus: 'VISA_HOLDER',
    visaType: 'Temporary Graduate (Subclass 485)',
    visaExpiryDate: '15/06/2025',
    hasDriverLicense: true,
    emergencyNextOfKin: 'Rohan KC',
    emergencyRelationship: 'Brother',
    emergencyAddress: '88 George Street',
    emergencySuburb: 'Parramatta',
    emergencyState: 'NSW',
    emergencyPostcode: '2150',
    emergencyMobile: '0411 222 333',
    tfnMasked: '• • • - • • • - 912',
    tfnEncrypted: encryptAES256('581938912'),
    superFundName: 'Hostplus',
    superMemberNumber: 'HP-449102',
    bankName: 'ANZ Bank',
    bankBranch: 'Parramatta Branch',
    accountName: 'Anita KC',
    bsbMasked: '012-•••',
    bsbEncrypted: encryptAES256('012-901'),
    accountNumberMasked: '••••••102',
    accountNumberEncrypted: encryptAES256('882910102'),
    leaveBalance: { annual: 14, sick: 8, carers: 3, longService: 0 },
    payslips: [],
    documents: [],
    kioskPin: '1234',
    clockState: 'CLOCKED_OUT',
  },
  {
    id: 'emp-40',
    employeeNumber: 'EMP-0040',
    username: 'ramesh.adhikari',
    firstName: 'Ramesh',
    lastName: 'Adhikari',
    email: 'ramesh.adhikari@company.com',
    mobilePhone: '0401 234 567',
    dateOfBirth: '10/11/1988',
    startDate: '10/05/2025',
    gender: 'Male',
    address: '42 Railway Parade',
    suburb: 'Kogarah',
    state: 'NSW',
    postcode: '2217',
    department: 'Administration',
    jobTitle: 'Operations Coordinator',
    workLocation: 'Rockdale, NSW',
    reportsTo: 'Operations Lead',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    citizenStatus: 'CITIZEN',
    hasDriverLicense: true,
    emergencyNextOfKin: 'Sunita Adhikari',
    emergencyRelationship: 'Wife',
    emergencyAddress: '42 Railway Parade',
    emergencySuburb: 'Kogarah',
    emergencyState: 'NSW',
    emergencyPostcode: '2217',
    emergencyMobile: '0499 111 222',
    tfnMasked: '• • • - • • • - 331',
    tfnEncrypted: encryptAES256('710291331'),
    superFundName: 'Aware Super',
    superMemberNumber: 'AWS-102941',
    bankName: 'Westpac',
    bankBranch: 'Kogarah Branch',
    accountName: 'Ramesh Adhikari',
    bsbMasked: '032-•••',
    bsbEncrypted: encryptAES256('032-441'),
    accountNumberMasked: '••••••554',
    accountNumberEncrypted: encryptAES256('993411554'),
    leaveBalance: { annual: 20, sick: 12, carers: 5, longService: 30 },
    payslips: [],
    documents: [],
    kioskPin: '5678',
    clockState: 'CLOCKED_OUT',
  },
  {
    id: 'emp-39',
    employeeNumber: 'EMP-0039',
    username: 'nisha.pokharel',
    firstName: 'Nisha',
    lastName: 'Pokharel',
    email: 'nisha.pokharel@company.com',
    mobilePhone: '0415 678 901',
    dateOfBirth: '05/09/1993',
    startDate: '05/05/2025',
    gender: 'Female',
    address: '19 Oxford Street',
    suburb: 'Bondi Junction',
    state: 'NSW',
    postcode: '2022',
    department: 'Sales & Marketing',
    jobTitle: 'Brand Strategist',
    workLocation: 'Sydney CBD, NSW',
    reportsTo: 'Head of Growth',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    citizenStatus: 'PERMANENT_RESIDENT',
    visaExpiryDate: '20/07/2025',
    hasDriverLicense: true,
    emergencyNextOfKin: 'Bikash Pokharel',
    emergencyRelationship: 'Father',
    emergencyAddress: '19 Oxford Street',
    emergencySuburb: 'Bondi Junction',
    emergencyState: 'NSW',
    emergencyPostcode: '2022',
    emergencyMobile: '0415 000 111',
    tfnMasked: '• • • - • • • - 882',
    tfnEncrypted: encryptAES256('482910882'),
    superFundName: 'REST Super',
    superMemberNumber: 'RST-991024',
    bankName: 'NAB',
    bankBranch: 'Bondi Branch',
    accountName: 'Nisha Pokharel',
    bsbMasked: '082-•••',
    bsbEncrypted: encryptAES256('082-124'),
    accountNumberMasked: '••••••990',
    accountNumberEncrypted: encryptAES256('338190990'),
    leaveBalance: { annual: 15, sick: 7, carers: 4, longService: 10 },
    payslips: [],
    documents: [],
    kioskPin: '9988',
    clockState: 'CLOCKED_OUT',
  },
  {
    id: 'emp-38',
    employeeNumber: 'EMP-0038',
    username: 'birendra.bhandari',
    firstName: 'Birendra',
    lastName: 'Bhandari',
    email: 'birendra.bhandari@company.com',
    mobilePhone: '0400 111 222',
    dateOfBirth: '19/02/1990',
    startDate: '01/05/2025',
    gender: 'Male',
    address: '7 Princess Highway',
    suburb: 'Rockdale',
    state: 'NSW',
    postcode: '2216',
    department: 'Production (Rockdale)',
    jobTitle: 'Production Lead',
    workLocation: 'Rockdale, NSW',
    reportsTo: 'Plant Manager',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    citizenStatus: 'VISA_HOLDER',
    visaType: 'Work Visa',
    visaExpiryDate: '10/09/2026',
    hasDriverLicense: true,
    emergencyNextOfKin: 'Sarita Bhandari',
    emergencyRelationship: 'Sister',
    emergencyAddress: '7 Princess Highway',
    emergencySuburb: 'Rockdale',
    emergencyState: 'NSW',
    emergencyPostcode: '2216',
    emergencyMobile: '0400 333 444',
    tfnMasked: '• • • - • • • - 149',
    tfnEncrypted: encryptAES256('193849149'),
    superFundName: 'AustralianSuper',
    superMemberNumber: 'AUS-449182',
    bankName: 'Commonwealth Bank',
    bankBranch: 'Rockdale Branch',
    accountName: 'Birendra Bhandari',
    bsbMasked: '062-•••',
    bsbEncrypted: encryptAES256('062-990'),
    accountNumberMasked: '••••••321',
    accountNumberEncrypted: encryptAES256('774819321'),
    leaveBalance: { annual: 10, sick: 10, carers: 5, longService: 20 },
    payslips: [],
    documents: [],
    kioskPin: '2233',
    clockState: 'CLOCKED_OUT',
  },
  {
    id: 'emp-01',
    employeeNumber: 'EMP-0001',
    username: 'rajesh.kumar',
    firstName: 'Rajesh',
    lastName: 'Kumar',
    email: 'rajesh.kumar@company.com',
    mobilePhone: '0412 888 777',
    dateOfBirth: '12/04/1992',
    startDate: '10/01/2023',
    gender: 'Male',
    address: '55 Coleridge Street',
    suburb: 'Riverwood',
    state: 'NSW',
    postcode: '2210',
    department: 'Production (Riverwood)',
    jobTitle: 'Senior Machine Operator',
    workLocation: 'Riverwood, NSW',
    reportsTo: 'Binod Gurung',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    citizenStatus: 'VISA_HOLDER',
    visaType: 'Subclass 482 TSS',
    visaExpiryDate: '30/05/2025',
    hasDriverLicense: true,
    emergencyNextOfKin: 'Sunil Kumar',
    emergencyRelationship: 'Brother',
    emergencyAddress: '55 Coleridge Street',
    emergencySuburb: 'Riverwood',
    emergencyState: 'NSW',
    emergencyPostcode: '2210',
    emergencyMobile: '0412 111 333',
    tfnMasked: '• • • - • • • - 720',
    tfnEncrypted: encryptAES256('992819720'),
    superFundName: 'Hostplus',
    superMemberNumber: 'HP-102941',
    bankName: 'St George Bank',
    bankBranch: 'Riverwood Branch',
    accountName: 'Rajesh Kumar',
    bsbMasked: '112-•••',
    bsbEncrypted: encryptAES256('112-879'),
    accountNumberMasked: '••••••442',
    accountNumberEncrypted: encryptAES256('449102442'),
    leaveBalance: { annual: 6, sick: 4, carers: 2, longService: 5 },
    payslips: [],
    documents: [],
    kioskPin: '7744',
    clockState: 'CLOCKED_OUT',
  },
  {
    id: 'emp-02',
    employeeNumber: 'EMP-0002',
    username: 'priya.sharma',
    firstName: 'Priya',
    lastName: 'Sharma',
    email: 'priya.sharma@company.com',
    mobilePhone: '0420 999 111',
    dateOfBirth: '28/07/1995',
    startDate: '14/03/2024',
    gender: 'Female',
    address: '102 Crown Street',
    suburb: 'Surry Hills',
    state: 'NSW',
    postcode: '2010',
    department: 'Design',
    jobTitle: 'Visual Designer',
    workLocation: 'Sydney CBD, NSW',
    reportsTo: 'Creative Director',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    citizenStatus: 'VISA_HOLDER',
    visaType: 'Graduate Visa 485',
    visaExpiryDate: '07/06/2025',
    hasDriverLicense: false,
    emergencyNextOfKin: 'Deepak Sharma',
    emergencyRelationship: 'Father',
    emergencyAddress: '102 Crown Street',
    emergencySuburb: 'Surry Hills',
    emergencyState: 'NSW',
    emergencyPostcode: '2010',
    emergencyMobile: '0420 444 888',
    tfnMasked: '• • • - • • • - 611',
    tfnEncrypted: encryptAES256('391029611'),
    superFundName: 'AustralianSuper',
    superMemberNumber: 'AUS-881920',
    bankName: 'Commonwealth Bank',
    bankBranch: 'Surry Hills Branch',
    accountName: 'Priya Sharma',
    bsbMasked: '062-•••',
    bsbEncrypted: encryptAES256('062-000'),
    accountNumberMasked: '••••••194',
    accountNumberEncrypted: encryptAES256('109482194'),
    leaveBalance: { annual: 12, sick: 6, carers: 4, longService: 0 },
    payslips: [],
    documents: [],
    kioskPin: '3322',
    clockState: 'CLOCKED_OUT',
  },
  {
    id: 'emp-03',
    employeeNumber: 'EMP-0003',
    username: 'binod.gurung',
    firstName: 'Binod',
    lastName: 'Gurung',
    email: 'binod.gurung@company.com',
    mobilePhone: '0433 555 888',
    dateOfBirth: '03/01/1986',
    startDate: '10/02/2021',
    gender: 'Male',
    address: '15 Market Street',
    suburb: 'Rockdale',
    state: 'NSW',
    postcode: '2216',
    department: 'Production (Rockdale)',
    jobTitle: 'Plant Supervisor',
    workLocation: 'Rockdale, NSW',
    reportsTo: 'Operations Manager',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    citizenStatus: 'VISA_HOLDER',
    visaType: 'Work TSS 482',
    visaExpiryDate: '12/06/2025',
    hasDriverLicense: true,
    emergencyNextOfKin: 'Maya Gurung',
    emergencyRelationship: 'Wife',
    emergencyAddress: '15 Market Street',
    emergencySuburb: 'Rockdale',
    emergencyState: 'NSW',
    emergencyPostcode: '2216',
    emergencyMobile: '0433 111 222',
    tfnMasked: '• • • - • • • - 504',
    tfnEncrypted: encryptAES256('884910504'),
    superFundName: 'Cbus Super',
    superMemberNumber: 'CB-994821',
    bankName: 'ANZ Bank',
    bankBranch: 'Rockdale Branch',
    accountName: 'Binod Gurung',
    bsbMasked: '012-•••',
    bsbEncrypted: encryptAES256('012-334'),
    accountNumberMasked: '••••••712',
    accountNumberEncrypted: encryptAES256('559102712'),
    leaveBalance: { annual: 18, sick: 10, carers: 6, longService: 35 },
    payslips: [],
    documents: [],
    kioskPin: '6655',
    clockState: 'CLOCKED_OUT',
  }
];

export const INITIAL_LEAVE_REQUESTS: LeaveRequest[] = [
  {
    id: 'lr-101',
    employeeId: 'emp-42',
    employeeName: 'Suman Thapa',
    employeeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Production (Riverwood)',
    leaveType: 'SICK',
    startDate: '12/08/2026',
    endDate: '13/08/2026',
    totalDays: 2,
    reason: 'Severe flu and fever, medical certificate attached.',
    status: 'APPROVED',
    submittedAt: '12/08/2026 06:25 AM',
    submittedBefore7AM: true,
    isAdvanceNoticeMet: true,
    advanceNoticeDays: 0,
    certificateUploaded: true,
    certificateUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=1000&auto=format&fit=crop&q=80',
    reminderCount: 0,
    reviewedBy: 'Admin User',
    reviewedAt: '12/08/2026 08:30 AM',
  },
  {
    id: 'lr-102',
    employeeId: 'emp-42',
    employeeName: 'Suman Thapa',
    employeeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Production (Riverwood)',
    leaveType: 'ANNUAL',
    startDate: '22/09/2026',
    endDate: '26/09/2026',
    totalDays: 5,
    reason: 'Family trip to Gold Coast.',
    status: 'APPROVED',
    submittedAt: '15/08/2026 10:15 AM',
    isAdvanceNoticeMet: true,
    advanceNoticeDays: 38,
    certificateUploaded: false,
    reminderCount: 0,
    reviewedBy: 'Admin User',
    reviewedAt: '16/08/2026 09:00 AM',
  },
  {
    id: 'lr-103',
    employeeId: 'emp-41',
    employeeName: 'Anita KC',
    employeeAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    department: 'Design',
    leaveType: 'ANNUAL',
    startDate: '28/08/2026',
    endDate: '01/09/2026',
    totalDays: 5,
    reason: 'Personal time off for family event.',
    status: 'PENDING',
    submittedAt: '18/08/2026 04:30 PM',
    isAdvanceNoticeMet: true,
    advanceNoticeDays: 10,
    certificateUploaded: false,
    reminderCount: 0,
  },
  {
    id: 'lr-104',
    employeeId: 'emp-01',
    employeeName: 'Rajesh Kumar',
    employeeAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    department: 'Production (Riverwood)',
    leaveType: 'SICK',
    startDate: '19/08/2026',
    endDate: '19/08/2026',
    totalDays: 1,
    reason: 'Migraine and back spasm.',
    status: 'PENDING',
    submittedAt: '19/08/2026 06:48 AM',
    submittedBefore7AM: true,
    isAdvanceNoticeMet: true,
    advanceNoticeDays: 0,
    certificateUploaded: false,
    reminderCount: 1,
  }
];

export const INITIAL_ALERTS: ComplianceAlert[] = [
  {
    id: 'alt-1',
    employeeId: 'emp-01',
    employeeName: 'Rajesh Kumar',
    employeeAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    department: 'Production (Riverwood)',
    type: 'VISA_EXPIRY',
    title: 'Visa Expiring Soon',
    description: 'Subclass 482 TSS Visa expires in 12 days.',
    dueDate: '30/05/2025',
    daysRemaining: 12,
    severity: 'URGENT',
  },
  {
    id: 'alt-2',
    employeeId: 'emp-02',
    employeeName: 'Priya Sharma',
    employeeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Design',
    type: 'VISA_EXPIRY',
    title: 'Visa Expiring Soon',
    description: 'Graduate Visa 485 expires in 20 days.',
    dueDate: '07/06/2025',
    daysRemaining: 20,
    severity: 'WARNING',
  },
  {
    id: 'alt-3',
    employeeId: 'emp-03',
    employeeName: 'Binod Gurung',
    employeeAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    department: 'Production (Rockdale)',
    type: 'VISA_EXPIRY',
    title: 'Visa Expiring Soon',
    description: 'Work TSS 482 expires in 25 days.',
    dueDate: '12/06/2025',
    daysRemaining: 25,
    severity: 'WARNING',
  },
  {
    id: 'alt-4',
    employeeId: 'emp-42',
    employeeName: 'Suman Thapa',
    employeeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Production (Riverwood)',
    type: 'LICENSE_EXPIRY',
    title: 'Driver License Verification',
    description: 'Uploaded license document is pending HR verification.',
    dueDate: '30/08/2026',
    daysRemaining: 45,
    severity: 'INFO',
  }
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    recipient: 'ADMIN',
    title: 'New Sick Leave Submitted',
    message: 'Rajesh Kumar submitted 1 day sick leave for today before 7:00 AM.',
    type: 'LEAVE_REQUEST',
    timestamp: '10 minutes ago',
    read: false,
  },
  {
    id: 'notif-2',
    recipient: 'ADMIN',
    title: 'Annual Leave Request',
    message: 'Anita KC submitted an annual leave request (5 days).',
    type: 'LEAVE_REQUEST',
    timestamp: '2 hours ago',
    read: false,
  },
  {
    id: 'notif-3',
    recipient: 'STAFF',
    recipientId: 'emp-42',
    title: 'Leave Approved',
    message: 'Your annual leave request (22/09 - 26/09) was approved by Admin.',
    type: 'LEAVE_STATUS',
    timestamp: '1 day ago',
    read: true,
  },
  {
    id: 'notif-4',
    recipient: 'STAFF',
    recipientId: 'emp-42',
    title: 'Payslip Available',
    message: 'Your payslip for period ending 15 May 2025 ($1,245.80) is ready.',
    type: 'GENERAL',
    timestamp: '3 days ago',
    read: false,
  }
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    "id": "aud-1789111800000",
    "action": "SYSTEM_SETTINGS_UPDATED",
    "targetType": "Settings",
    "targetId": "audit",
    "details": "Updated audit log retention period to 7 days with continuous auto-purge",
    "actorId": "usr-1",
    "actorName": "Super Admin",
    "actorRole": "Admin",
    "timestamp": "11/09/2026, 12:30:15 pm AEST",
    "ipAddress": "127.0.0.1 (Localhost)"
  },
  {
    "id": "aud-1789100062000",
    "action": "VIEW_ENCRYPTED_BANK_DETAILS",
    "targetType": "Employee",
    "targetId": "emp-42 (Suman Thapa)",
    "details": "Decrypted BSB and Account Number for payroll audit validation.",
    "actorId": "usr-1",
    "actorName": "Super Admin",
    "actorRole": "Admin",
    "timestamp": "11/09/2026, 09:14:22 am AEST",
    "ipAddress": "203.14.182.91 (Sydney, AU)"
  },
  {
    "id": "aud-1789040710000",
    "action": "MANUAL_TIMECARD_ADJUST",
    "targetType": "Timecard",
    "targetId": "tc-01",
    "details": "Adjusted meal break and clocked net hours for Rajesh Kumar.",
    "actorId": "usr-1",
    "actorName": "Super Admin",
    "actorRole": "Admin",
    "timestamp": "10/09/2026, 04:45:10 pm AEST",
    "ipAddress": "203.14.182.91 (Sydney, AU)"
  },
  {
    "id": "aud-1789031733000",
    "action": "ADMIN_CREDENTIALS_UPDATED",
    "targetType": "User",
    "targetId": "usr-1",
    "details": "Admin credentials and login password updated for Super Admin.",
    "actorId": "usr-1",
    "actorName": "Super Admin",
    "actorRole": "Admin",
    "timestamp": "10/09/2026, 02:15:33 pm AEST",
    "ipAddress": "127.0.0.1 (Localhost)"
  },
  {
    "id": "aud-1788934805000",
    "action": "APPROVE_LEAVE_REQUEST",
    "targetType": "LeaveRequest",
    "targetId": "lr-103 (Anita KC)",
    "details": "Approved 3 days Annual Leave starting 18/09/2026.",
    "actorId": "usr-1",
    "actorName": "Super Admin",
    "actorRole": "Admin",
    "timestamp": "09/09/2026, 11:20:05 am AEST",
    "ipAddress": "203.14.182.91 (Sydney, AU)"
  },
  {
    "id": "aud-1788838200000",
    "action": "SYSTEM_BACKUP_EXPORT",
    "targetType": "Backup",
    "targetId": "all",
    "details": "Exported comprehensive system backup archive (.json).",
    "actorId": "usr-1",
    "actorName": "Super Admin",
    "actorRole": "Admin",
    "timestamp": "08/09/2026, 08:30:00 am AEST",
    "ipAddress": "203.14.182.91 (Sydney, AU)"
  },
  {
    "id": "aud-1788775845000",
    "action": "VISA_STATUS_VERIFIED",
    "targetType": "Compliance",
    "targetId": "emp-01 (Rajesh Kumar)",
    "details": "Verified VEVO work entitlements and Subclass 482 visa compliance.",
    "actorId": "usr-1",
    "actorName": "Super Admin",
    "actorRole": "Admin",
    "timestamp": "07/09/2026, 03:10:45 pm AEST",
    "ipAddress": "203.14.182.91 (Sydney, AU)"
  }
];

export const INITIAL_TIMECARDS: TimecardRecord[] = [
  {
    id: 'tc-live-01',
    employeeId: 'emp-42',
    employeeName: 'Suman Thapa',
    employeeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Production (Riverwood)',
    date: getTodayFormatted(),
    clockIn: '07:30 AM',
    clockInTimestamp: Date.now() - (3 * 3600 + 42 * 60 + 15) * 1000,
    breakMinutes: 0,
    durationSeconds: 0,
    totalHours: 0,
    overtimeHours: 0,
    status: 'CLOCKED_IN',
    notes: 'Morning shift on Large Format Roland printer.'
  },
  {
    id: 'tc-01',
    employeeId: 'emp-42',
    employeeName: 'Suman Thapa',
    employeeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Production (Riverwood)',
    date: '17 Aug 2026',
    clockIn: '07:30 AM',
    clockOut: '04:00 PM',
    breakMinutes: 30,
    durationSeconds: 28800,
    totalHours: 8.0,
    overtimeHours: 0,
    status: 'COMPLETED',
    notes: 'Morning shift on Large Format Roland printer.'
  },
  {
    id: 'tc-02',
    employeeId: 'emp-42',
    employeeName: 'Suman Thapa',
    employeeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Production (Riverwood)',
    date: '18 Aug 2026',
    clockIn: '07:28 AM',
    clockOut: '04:05 PM',
    breakMinutes: 30,
    durationSeconds: 29220,
    totalHours: 8.12,
    overtimeHours: 0,
    status: 'COMPLETED',
    notes: 'Die-cutting and packaging line.'
  },
  {
    id: 'tc-03',
    employeeId: 'emp-42',
    employeeName: 'Suman Thapa',
    employeeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Production (Riverwood)',
    date: '19 Aug 2026',
    clockIn: '07:31 AM',
    clockOut: '04:00 PM',
    breakMinutes: 30,
    durationSeconds: 28740,
    totalHours: 7.98,
    overtimeHours: 0,
    status: 'COMPLETED',
    notes: 'Rockdale express order batching.'
  },
  {
    id: 'tc-04',
    employeeId: 'emp-41',
    employeeName: 'Anita KC',
    employeeAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    department: 'Design',
    date: '19 Aug 2026',
    clockIn: '08:30 AM',
    clockOut: '05:00 PM',
    breakMinutes: 30,
    durationSeconds: 28800,
    totalHours: 8.0,
    overtimeHours: 0,
    status: 'COMPLETED',
    notes: 'Client proofing & 3D mockups.'
  },
  {
    id: 'tc-05',
    employeeId: 'emp-40',
    employeeName: 'Ramesh Adhikari',
    employeeAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    department: 'Administration',
    date: '18 Aug 2026',
    clockIn: '08:00 AM',
    clockOut: '04:30 PM',
    breakMinutes: 30,
    durationSeconds: 28800,
    totalHours: 8.0,
    overtimeHours: 0,
    status: 'COMPLETED',
    notes: 'Operations logistics dispatch.'
  },
  {
    id: 'tc-06',
    employeeId: 'emp-39',
    employeeName: 'Nisha Pokharel',
    employeeAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    department: 'Sales & Marketing',
    date: '17 Aug 2026',
    clockIn: '08:45 AM',
    clockOut: '05:15 PM',
    breakMinutes: 30,
    durationSeconds: 28800,
    totalHours: 8.0,
    overtimeHours: 0,
    status: 'COMPLETED',
    notes: 'Campaign onboarding.'
  }
];

